<?php

declare(strict_types=1);
/**
 * ListingDataTest.
 *
 * PHP version 7.2
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Reddit.com.
 *
 * Reddit.com API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Flexolabs\RedditClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListingDataTest Class Doc Comment.
 *
 * @category    Class
 * @description ListingData
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 *
 * @internal
 *
 * @small
 */
final class ListingDataTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown(): void
    {
    }

    /**
     * Test "ListingData".
     */
    public function testListingData(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modhash".
     */
    public function testPropertyModhash(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dist".
     */
    public function testPropertyDist(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "children".
     */
    public function testPropertyChildren(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "after".
     */
    public function testPropertyAfter(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "before".
     */
    public function testPropertyBefore(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }
}
