<?php
/**
 * UserApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Flexolabs\RedditClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Reddit.com
 *
 * Reddit.com API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Flexolabs\RedditClient;

use \Flexolabs\RedditClient\Configuration;
use \Flexolabs\RedditClient\ApiException;
use \Flexolabs\RedditClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Flexolabs\RedditClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSaved
     *
     * Get user saved things.
     *
     */
    public function testGetSaved()
    {
    }

    /**
     * Test case for me
     *
     * Returns the identity of the user..
     *
     */
    public function testMe()
    {
    }
}
