<?php

declare(strict_types=1);
/**
 * UserApiTest
 * PHP version 7.2.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Reddit.com.
 *
 * Reddit.com API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Flexolabs\RedditClient\Test\Api;

use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 *
 * @small
 */
final class UserApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown(): void
    {
    }

    /**
     * Test case for getSaved.
     *
     * Get user saved things.
     */
    public function testGetSaved(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for me.
     *
     * Returns the identity of the user..
     */
    public function testMe(): void
    {
        // TODO: implement
        static::markTestIncomplete('Not implemented');
    }
}
